on: workflow_dispatch
permissions:
  id-token: write
jobs:
  install-cloudsmith-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with:
          oidc-namespace: 'muditns'
          oidc-service-slug: 'muditsvc'

      - name: Verify Cloudsmith CLI Installation
        run: |
          cloudsmith --version
